### ISSUE TITLE
beginner question

### ISSUE THREAD

**Issue by sureloc** [T3m3z/spotprices2ha#14]
Pardon the stupid question, but after uploading the spot-price.yaml file, exactly where in the configuration.yaml is one supposed to paste in this?

"homeassistant: # Find this row and if it doesn't exists, you can copypaste this whole block to the file.
  packages: # NEW AND IMPORTANT ROW, NOTE INDENTATION
    pack_1: !include spot-price.yaml # NEW AND IMPORTANT ROW, NOTE INDENTATION
  # There might be code here. Leave it as is."
  

 On a fresh install mine looks like this:

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

**Comment by jumakki** [comment]
If line  
`homeassistant:`
doesn't exist in your configuration.yaml, then you can add it and other lines to the beginning of the file. In reality place doesn't matter as long as packages and pack_1 lines are under it.
Beginning of my file is like this:
```
homeassistant:
  packages:
    pack_1: !include spot-price.yaml

  # Name of the location where Home Assistant is running
  name: Home
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Helsinki
  country: FI
  currency: EUR
```
You should add only those 3 first lines.
