### ISSUE TITLE
"sensor.shf_electricity_price_now" not working after HA update to 2023.5.0

### ISSUE THREAD

**Issue by Ilpo55** [T3m3z/spotprices2ha#15]
After HA update to version 2023.5.0  "sensor.shf_electricity_price_now" is unknown.
I replaced line `state: '{{ state_attr("sensor.shf_electricity_price_now", "today_prices")[now().hour] }}'`
with line `state: '{{ state_attr("sensor.shf_electricity_price", "data")[now().hour]["PriceWithTax"]}}'`

Now it works.
Is that fix OK?

**Comment by lassikos** [comment]
Same issue here:

Logger: homeassistant
Source: components/sensor/__init__.py:583
First occurred: 11:54:51 (12 occurrences)
Last logged: 12:15:26

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 579, in state
    numerical_value = int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template_entity.py", line 379, in _async_template_startup
    result_info.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 953, in async_refresh
    self._refresh(None)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1133, in _refresh
    self.hass.async_run_hass_job(self._job, event, updates)
  File "/usr/src/homeassistant/homeassistant/core.py", line 607, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/helpers/template_entity.py", line 348, in _handle_results
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 649, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 591, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 583, in state
    raise ValueError(
ValueError: **Sensor sensor.shf_electricity_price_now has device class monetary, state class None unit €/kWh and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value:  (<class 'str'>)**

**Comment by vikohub** [comment]
> After HA update to version 2023.5.0 "sensor.shf_electricity_price_now" is unknown. I replaced line `state: '{{ state_attr("sensor.shf_electricity_price_now", "today_prices")[now().hour] }}'` with line `state: '{{ state_attr("sensor.shf_electricity_price", "data")[now().hour]["PriceWithTax"]}}'`
> 
> Now it works. Is that fix OK?

Works for me too.

**Comment by lakofsth** [comment]
The fix seems to miss the additional "input_number.shf_price1_slider" price overhead which you can use to add in margin, transport and tax.

**Comment by Ilpo55** [comment]
>The fix seems to miss the additional "input_number.shf_price1_slider"

I think that the problem is with "SHF Control Factor "
Can you test if you modify that part of the yaml. Original line is commented.

```
  - sensor:
    - name: SHF Control Factor 0-1
      unique_id: shf_control_factor_0-1
      unit_of_measurement: factor
      icon: mdi:gauge
      state: '{{ (states("sensor.shf_control_factor_1") | float /2 + 0.5) | default(0) }}'
#      state: '{{ (states("sensor.shf_control_factor_1") | float /2 + 0.5) | default("Unknown") }}'
```
and

```
  - sensor:
    - name: SHF Control Factor +-1
      unique_id: shf_control_factor_+-1
      unit_of_measurement: factor
      icon: mdi:gauge
      state: '{{ state_attr("sensor.shf_control_factor_1", "today_values")[now().hour] | default(0) }}'
#      state: '{{ state_attr("sensor.shf_control_factor_1", "today_values")[now().hour] | default("Unknown") }}'
```

I don't use extra prices so I don't have that part of code in my yaml.
