### ISSUE TITLE
HA + Apexchart + Tariff prices

### ISSUE THREAD

**Issue by heijjan** [T3m3z/spotprices2ha#4]
Hi,

Thanks for a great and simple solution for the SPOT price analysis. I was wondering if it was possible to implement the tariff prices (nigh/day) to the ApexChart configuration so that the tariff prices would be added on top of the SPOT price for every hour? I just can't figure out how to do it. Another solution would be to implement the tariff to the configuration of the main sensor shf_electricity_price somehow.

Our tariffs are 6.8c/kWh during 7-22 and 5.24c/kWh during 22-07.

**Comment by T3m3z** [comment]
Hello!

If you want to add the transmission and other extra fees only to the chart, then maybe this quick hack could work:
```yaml
type: custom:apexcharts-card
graph_span: 48h
experimental:
  color_threshold: true
show:
  last_updated: true
header:
  title: Electricity price (c/kWh)
  show: true
  show_states: true
  colorize_states: true
span:
  start: day
yaxis:
  - min: 0
    decimals: 2
    apex_config:
      forceNiceScale: true
now:
  show: true
  label: Now
series:
  - entity: sensor.shf_electricity_price
    show:
      in_header: false
      extremas: true
    type: column
    color: lightgray
    float_precision: 2
    data_generator: |
      var extra_fees = [5.46, 5.46, 5.46, 5.46, 5.46, 5.46, 5.46, 7.02, 7.02, 7.02, 7.02, 7.02, 7.02, 7.02, 7.02, 7.02, 7.02, 7.02, 7.02, 7.02, 7.02, 7.02, 5.46, 5.46 ] ;
      return entity.attributes.data.map((d, index) => {
        var tempdate = new Date(d["DateTime"]);
        var hour = tempdate.getHours();
        return [tempdate.getTime(), entity.attributes.data[index]["PriceWithTax"]*100+extra_fees[hour]];
      });
    color_threshold:
      - value: 0
        color: 368f39
      - value: 10
        color: a3b34d
      - value: 20
        color: ffd57e
      - value: 30
        color: f18c56
      - value: 40
        color: de425b
  - entity: sensor.shf_electricity_price
    show:
      in_header: true
      header_color_threshold: true
      in_chart: false
    type: line
    color: lightgray
    float_precision: 2
    stroke_width: 0
    data_generator: |
      var extra_fees = [5.46, 5.46, 5.46, 5.46, 5.46, 5.46, 5.46, 7.02, 7.02, 7.02, 7.02, 7.02, 7.02, 7.02, 7.02, 7.02, 7.02, 7.02, 7.02, 7.02, 7.02, 7.02, 5.46, 5.46 ] ;
      var currentTime = new Date().setMinutes(0, 0, 0);
      let currentPrice = entity.attributes.data.find(d => {
        return new Date(d["DateTime"]).getTime() === currentTime;
      })["PriceWithTax"];
      return entity.attributes.data.map((d, index) => {
        var t = new Date();
        return [new Date(d["DateTime"]).getTime(), currentPrice*100 + extra_fees[t.getHours()]];
      });
    color_threshold:
      - value: 0
        color: 368f39
      - value: 10
        color: a3b34d
      - value: 20
        color: ffd57e
      - value: 30
        color: f18c56
      - value: 40
        color: de425b
```

Currently implementing transmission fees + other extra fees to the data loader isn't that simple as this package is using Restful sensor included in the HomeAssistant. Modifying the Array of prices isn't right now possible (or at least easy) as Template Sensors always output a String. But I'm going to think about this as I see the value of this. Sometimes day/night transmission fees could change the outcome of some scripts.
